services:
  - type: web
    name: todo-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: todo-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: todo-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: todo-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: todo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: todo-db
          property: password
            - key: HIBERNATE_DIALECT
                    value: org.hibernate.dialect.PostgreSQLDialect
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_FONTS_API_KEY
        value: AIzaSyDkSoKtrV_WGBXdzqw_hHhAxITX8RAqlew

databases:
  - name: todo-db
    plan: free
    databaseName: todo
